### ISSUE TITLE
Cluster name / ID field empty in "Rubrik Stats"

### ISSUE THREAD

**Issue by Darrenswift** [rubrikinc/rubrik-addon-for-splunk#18]
**Expected Behavior**

Under Rubrik stat's within SNOW I would of expected to see "Cluster name" populated with either clusterID or cluster name itself. 

**Current Behavior**

Current display for "cluster name" is (empty)

**Failure Information (for bugs)**

No logs to attach only screenshot 

![image](https://user-images.githubusercontent.com/32131794/70141660-735f9600-168f-11ea-9439-113ba26242b1.png)

Please help provide information about the failure if this is a bug.

**Steps to Reproduce**
Load SNOW
Navigate to Rubrik Stat's 
See screenshot 
Tested in customer deployment and also EMEA 1 Lab

Please provide detailed steps for reproducing the issue.

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Rubrik 5.0.3 latest GA
shrd1-rbk01.rubrikdemo.com
In events "cluster name" is populated it is only Rubrik stats which is the issue 
**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by Draper1** [comment]
Intended for SNOW not Splunk. Closing Issue.
