### ISSUE TITLE
Account config screen stuck on "Loading" - splunktcptoken dependency?

### ISSUE THREAD

**Issue by RickyBails** [rubrikinc/rubrik-addon-for-splunk#24]
In a fresh install of the Splunk Rubric add-on app (v112) on Splunk v8, the configuration screen for setting the user account is not working- permanently stuck on "Loading". A google search suggests this is a problem with the add-on builder but most of the solutions I've seen are mostly for developers to fix the build rather than end-users to hack the install.
Up to now we've been successfully using the rubrik add-on v1.0.1 on a Splunk 7.2.6 heavy forwarder. Now we are upgrading to Splunk 8.0.6 and I've done clean installs of both 1.1.1 and 1.1.2 version of the rubrik add-on. In both cases, going to the Configuration/Account screen to enter the rubrik account (the first step in the configs) results in that page stuck in an endless "Loading" state.
I ran this command...
> splunk cmd splunkd print-modinput-config --debug .
...and the output ended:
`No script to handle scheme "splunktcptoken" was found.  This modular input will be disabled.
Unable to find suitable script for scheme "" defined in the system context.  This scheme will not be initialized.
Scheme "TA_rubrik_splunk_add_on_account" is not initialized.`
...but I can't see where splunktcptoken is being referenced.
The only 2 dependencies documented are Splunk >V7 and the datasets add-on. Both these are met but is there another dependency here?
The HF I'm installing on is a fresh install of 8.0.6 which has python3 but the OS itself has python 2.6.6 as the default.
One thing I tried to do (as suggested somewhere) to fix this was to clone the inputs.conf and restmap.conf into a local dir and change all the references to 'python3' to 'python2' (in case the app is using the OS's python and not Splunk's python install) - it didn't work.
We're not able to upgrade the OS version of python at this time but if this is what's required we'll be able to do this soon.
Regards,
Richard Bailey
CMC Markets

**Comment by railroadmanuk** [comment]
Worked with Richard, and this was due to incorrect credentials. Working on improving logging and error handling for v1.1.3.

**Comment by splunker9** [comment]
Hi there,
I am running into same issue, can you please elaborate the resolution. Screen does not load to add an account, where would we enter credentials ?. 
Regards,
Splunker9
