### ISSUE TITLE
io_stats API does not work after upgrading Rubrik to 5.x

### ISSUE THREAD

**Issue by JanPillarRubrik** [rubrikinc/rubrik-addon-for-splunk#9]
**Expected Behavior**

Statistics provided by io_stats are correctly gathered in 1 minute intervals.

**Current Behavior**

After upgrading to Rubrik 5.0, the API call for io_stats does not work with 1 minute interval (range=-1min) as the statistics are gathered in 5 minute intervals on the cluster.

**Failure Information (for bugs)**

io_stats does not fail but returns empty output, which is most likely represented as 0.

**Steps to Reproduce**

1) Upgrade Rubrik cluster from 4.x (all data displayed correctly) to 5.0.

* Use numbered list.

**Context**

* Version of Rubrik: 5.0.0-p2

Based on the fact that statistics are gathered every 5 minutes, any API call for range smaller than 5min will not return any data.
The suggestion is to use range of 6 minutes and only pick one minute to collect the data from the output.
For example:

A) Gather -6min at 10:00 (range: 09:54-10:00).
B) Pick only data for 09:55-09:56 to be stored in Splunk.
C) Gather -6min at 10:01 (range: 09:55-10:01).
D) Pick only data for 09:56-09:57 to be stored in Splunk.
ETC.

**Comment by railroadmanuk** [comment]
We are actually using 10 mins as the range here, but have made a code change to fix this, validating and pushing to Splunkbase now

**Comment by railroadmanuk** [comment]
This is now pushed to Splunkbase, closing issue

**Comment by RickyBails** [comment]
Thanks for publishing a fix so quickly. The stats look a bit suspect however. Every 5 mins (on the 5 mins). we see all-zero values. The minute before those zero minutes the values are either much lower than usual or zero. I've attached a screenshot from the Capacity Dashboard.
![5minCycles](https://user-images.githubusercontent.com/47212596/55162591-0e4abc80-5160-11e9-96e7-578072517171.PNG)
What looks better than the previous version is that the other minutes are unique values, whereas the previous version would repeat the same values for 5 mins.
